### ISSUE TITLE
Avoid naming conflict with Cloud Foundry

### ISSUE THREAD

**Issue by schlomo** [cfn-sphere/cfn-sphere#101]
I just noticed that [Cloud Foundry](https://en.wikipedia.org/wiki/Cloud_Foundry) from [pivotal](http://pivotal.io/platform) also uses `cf` as the command line tool name.

Since they came first I would suggest to rename the cfn-sphere CLI from `cf` to e.g. `cfn-sphere` to make sure that we are future proof with a name that won't create conflicts with other software installed on users' desktops.

**Comment by konz** [comment]
Would you use Cloud Foundry CLI and cf-sphere at the same time?

**Comment by schlomo** [comment]
ATM we prevent people from using both which is IMHO bad style. And yes, I think that people might be using both, especially if they are now on Cloud Foundry and want to try out alternatives. How many users will try out cfn-sphere if they can't call it on the command line?

**Comment by marco-hoyer** [comment]
Changing an already well established binary name is not that easy without annoying users. This shouldn't be done without thinking twice.

**Comment by schlomo** [comment]
That is absolutely correct. And the later we change the name the bigger is the damage. I would suggest to change the actual name of the binary to something that is really unique and to make it easy to have a short alias for those who want.

Basically adding the following line to your `~/.bashrc` is enough:

```
alias cf=cfn-sphere
```

I would assume that all users of a command line tool will be able to perform this action.

**Comment by marco-hoyer** [comment]
I also would assume that nearly all users are able to define an alias but this is not the point. Renaming the binary would be an annoying change for users. They will have to write cfn-sphere which seems to be complicated for some or define an alias. Furthermore a lot of CI/CD jobs need to be modified. This is not that much of a problem but in fact I'm not seeing the balance of pain makes it feasible to rename the binary. There are lot of other tools with conflicting names and I would really like to see other people having this problem.

**Comment by esc** [comment]
I am against this, it's a case of premature optimization, please stop wasting time discussing this and close as `WONTFIX` instead. If it ever comes to this problem, @schlomo can grin into our faces and speak the phrase: "Told you so!!" but I am very willing to take this bet. :)

**Comment by esc** [comment]
I am going to close this now, please feel free to re-open if it really does become an issue.
