### ISSUE TITLE
Allow for Cloudformation templates with .template extenstion

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#105]
Hi,

It would be really great if you could allow for JSON Cloud Formation templates having a .template extension. This is the default used by the AWS Visual Studio SDK. Currently the SDK doesn't recognise .json files as Cloud Formation so doesn't apply all the Syntax highlighting etc. It will be a lot easier for me to sell cfn-sphere to the other team members if they don't have to rename files or change their IDE settings.

Thanks

**Comment by marco-hoyer** [comment]
Thx a lot. I will have a look at it this evening.

**Comment by marco-hoyer** [comment]
Could you please give me some insight into your use-case for this? From my perspective it is more or less confusing that there are .template files which are implicitly threaded as json. There for I would like to understand your problems here.

**Comment by jrudge-kcom** [comment]
Hi,

It's simple really, we use Visual Studio and the AWS SDK to write cloud formation. The Visual Studio SDK expects .template files and only does syntax highlighting and intelligence with that extension. I opened a support case with AWS to enable the use of JSON or Template extensions but there is no way to do it, so they have added it as a feature request, however SDK support for .json isn't going to happen anytime soon. The official extension for cloud formation templates is .template all the examples on the AWS snippets us this extension, so from that angle I am unsure why you would primarily use .JSON in a tool designed for use with Cloud Formation?

e.g. http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-sample-templates.html

Hope that helps.

Jonathan

**Comment by jrudge-kcom** [comment]
+ Just to add, I understand you can just rename the files, but that is an additional step and leads to duplicate files which isn't particularly desirable. We would much rather work in the native .template format.

**Comment by marco-hoyer** [comment]
Ah ok, interesting. I didn't know about the Visual Studio approach. Seems to be a good idea to support that.
