### ISSUE TITLE
output stack creation error even if stack is deleted super fast

### ISSUE THREAD

**Issue by matey-jack** [cfn-sphere/cfn-sphere#106]
We often get errors similar to this:

    26.07.2016 16:58:08 INFO: Stack create started
    26.07.2016 16:58:18 ERROR: Could not create regularS3objectDeleter: ValidationError: Stack [regularS3objectDeleter] does not exist

We found out that Cloudformation detects an error and deletes the stack faster than cfn-sphere's first poll for a status.

It would help if cfn-sphere would use Cloudformation's `--on-failure DO_NOTHING` option to prevent deletion of the stack, so the error message can be gotten and displayed. (cfn-sphere could delete the stack by itself afterwards.)

**Comment by marco-hoyer** [comment]
This is very interesting. As far as I could see the stack deletion takes enough time for cfn-sphere to get the event and display the error. This is why I configured it to delete stacks failed to create. What is the size of your stacks template? Is it rather short, like only one resource or so?

**Comment by marco-hoyer** [comment]
would this fit your needs?

**Comment by marco-hoyer** [comment]
This is already on the road
