### ISSUE TITLE
IAM Named Resource Capability

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#109]
I have hit a snag where I cannot perform a stack creation due to the IAM confirmation. However I am sure I had created IAM resources in another template. Can we please get a switch added to confirm IAM resource creation as per the CLI?

ERROR: Could not create stRarsDevSup01-IamInstancePolicyAndRoles: An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]

See the --capabilities section in the create stack docs, same applies to all the SDK's

http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack

https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html

**Comment by jrudge-kcom** [comment]
Ah, I think I know what this is. I have used the new ability to name IAM resources introduced around 1-2 weeks ago. This requires a slightly different capability. I can work around it for now but it would be good to add the CAPABILLITY_NAMED_IAM as well as CAPABILLITY_IAM

**Comment by marco-hoyer** [comment]
Good point, this is a fairly new capability. Will add it soon.
