### ISSUE TITLE
Parallel deployment for resources with equal dependancies

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#117]
It would be really useful if you could support sync/delete parallel operations so for instance 10 instances will deploy simultaneously instead of one by one. Same goes for delete operations.  This would save a lot of time.

**Comment by marco-hoyer** [comment]
I agree on that. As the tool is implemented in python, it is not trivial to do things in parallel. I will think about it but don't see it being implemented in short term.

**Comment by konz** [comment]
Threads are available in Python, I have successfully used them even as Python amateur. :-) They are not really executed in parallel, but as we are waiting for API responses most of the time this should be perfectly ok.

**Comment by marco-hoyer** [comment]
@konz I agree that there are solutions available and it might be possible to implement it. I usually see very ugly code when it comes to multiprocessing with python where you see that python is not designed for parallelism. I had always trouble getting it to work smoothly even for small apps. Doing it right might need massive changes. But there might be nicer solutions out there as those I know. @esc any suggestions?

**Comment by konz** [comment]
@marco-hoyer I don't mean multiprocessing, but threading. It's as simple as in Java :-)
See: https://gist.github.com/konz/2396b29713f45ed08ef15ccff353b85c.js

The more interesting refactoring would be would be to determine the stacks that can be executed concurrently and maintaining the right order otherwise.

**Comment by konz** [comment]
@jrudge-kcom you could give it a try if you dare. Only sync for now

**Comment by jrudge-kcom** [comment]
Hi,

I am happy to test. I am a Git N00b. Is there a simple way to get the code changes from this PR?

**Comment by esc** [comment]
You can (or should be able to) `pip install` from github:

```
pip install git+ssh://git@github.com/konz/cfn-sphere.git@parallel_execution
```

**Comment by esc** [comment]
If you do this in a throw-away virtualenvironment you should have no problems.

**Comment by rayhwangkcom** [comment]
Hi - picking this up - is it possible for us to continue testing this with the latest codebase + parallel execution?

**Comment by marco-hoyer** [comment]
This is way to old to pick it up again.
