### ISSUE TITLE
Support for additional stack configuration

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#119]
It would be nice to have cfn-sphere handle stack policies and also the brand new feature of service roles which allow users to define a specific role to be used by cloudformation to fulfill stack actions.

**Comment by esc** [comment]
Do you have more information about the service roles?

**Comment by esc** [comment]
Ah, I see the pull-request at #120

**Comment by marco-hoyer** [comment]
cfn doc just for information: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html
