### ISSUE TITLE
Unintended updates caused by config-git-repository tag

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#125]
With version 0.1.34 cfn-sphere automatically adds a config-git-repository tag with the repo url as value if the stack configuration resides within a git repository. This stack level tag gets propagated to the stacks resources depending on the resource type. In bad cases, the tag is automatically added to an RDS parameter group. This causes a database downtime which should not happen at all. 

This might be acceptable but possible inconsistencies are much worse. When the git project containing the stack configuration was checked out with https, the repository url is something like `https://host/space/repo.git` but when checked out with ssh it might be `user@host:space/repo.git`. This causes the config-git-repository tag value to differ depending on the environment on which the update is made.

**Comment by jrudge-kcom** [comment]
Is it possible to disable this functionality or have it as an optional switch?

**Comment by marco-hoyer** [comment]
We decided to remove the git repo tagging in favor of appending the repo url to the stacks description. This prevents unintended stack updates triggered by different working environments.
