### ISSUE TITLE
Git stack description opt out.

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#127]
Hi, 

The change you have introduced in 1.35 changes the stack description. Is it possible to have a switch to opt out of this functionality? It doesn't provide any value in our use case as the updates aren't run from a central repo. At least not yet so the appended description makes no sense. I also have concerns over what happens to the stack when the description changes. I will need to test that. 

Thanks

**Comment by jrudge-kcom** [comment]
Actually scrap the last part. I downgraded to 1.33 to test it. It appears it only gets modified with a stack update. It won't cause a stack update in itself.

**Comment by konz** [comment]
Indeed. This is the intention of the change: to use a less invasive location for this metadata. It will get applied with every update but does not trigger an update itself.

**Comment by marco-hoyer** [comment]
Additionally it will only appear if cfn-sphere detects a git repository. If you have none, there will be no modification. This is why we decided not to offer an opt-out switch.

**Comment by jrudge-kcom** [comment]
OK, it could just be the way we are using Git as we have a local fork and running the sync locally so it gives the name of my fork. At least it's obvious who last did an update, I will have a play with it. Thanks.

**Comment by marco-hoyer** [comment]
May we close this issue for now?

**Comment by jrudge-kcom** [comment]
Yes. that's fine.
