### ISSUE TITLE
0.1.36 breaks template validation on our templates

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#136]
Hi,

We tried 0.1.36 this week and discovered the template validation fails on some of our templates despite them passing the cloud formation api validation check. The issues crop up in the userdata sections and seem to be caused by the use of fn::join's and a mixture of strings and Refs/Fn::GettAtt  

e.g. 

"if [[ $ALLOCATION_ID ]]; then ${AWSCMD} ec2 associate-address --instance-id ${AWS_INSTANCE_ID} --allocation-id ${ALLOCATION_ID} --allow-reassociation --region ", { "Ref" : "AWS::Region" }, " --cli-connect-timeout 60 --cli-read-timeout 60", "|| ERROR_EXIT 'Failed to set EIP.'\n",

changing to

"if [[ $ALLOCATION_ID ]]; then ${AWSCMD} ec2 associate-address --instance-id ${AWS_INSTANCE_ID} --allocation-id ${ALLOCATION_ID} --allow-reassociation --region ", { "Ref" : "AWS::Region" }, " --cli-connect-timeout 60 --cli-read-timeout 60 || ERROR_EXIT 'Failed to set EIP.'\n",

resolves it but it's only in 0.1.36 cfn-sphere it's an issue, everything else works as expected. 

Jonathan

**Comment by marco-hoyer** [comment]
Hi, thanks for reporting. Can you maybe post a more complete example of the template part probably causing the error so I can reproduce it with a test?

**Comment by jrudge-kcom** [comment]
I'll see if I can come up with something when I get a moment.

**Comment by marco-hoyer** [comment]
@jrudge-kcom any news on this?

**Comment by jrudge-kcom** [comment]
Sorry, crazy busy at the moment. I will try and get something asap.

**Comment by jrudge-kcom** [comment]
@marco-hoyer here are two examples, one which fails your validation in 0.1.36/37 and one that passes. As you can see it's a simple reason why it does and is probably bad code really. However they both pass cloud formation validation and work <0.1.36 (Tested in 0.1.33) so there must be something odd going on somewhere. Just so you are working templates, they are just to prove the validation bug.


[cfn-broken-examples.zip](https://github.com/cfn-sphere/cfn-sphere/files/775000/cfn-broken-examples.zip)

**Comment by rayhwangkcom** [comment]
@marco-hoyer - any updates? 

I am a CFN sphere noob but basically it's this check that breaks it for us.
https://github.com/cfn-sphere/cfn-sphere/blob/master/src/main/python/cfn_sphere/template/transformer.py#L81

It was working before as we had a space but it broke our code now that you are now correctly applying the strip function the startswith comparison.

**Comment by marco-hoyer** [comment]
Hi, didn't see the update here. I will have a look at it.

**Comment by rayhwangkcom** [comment]
Thanks @marco-hoyer. Let me know if you need anything.

**Comment by rayhwangkcom** [comment]
I've created a monkey patch locally which updates line 84 to be:
`if isinstance(value, string_types) and value.strip().startswith('|') and not value.strip().startswith('||'):` 

to work around the problem for now - but I can't image this to be a long term solution.

**Comment by marco-hoyer** [comment]
It took some time to understand the issue but the comment from @rayhwangkcom helped a lot. I improved the validation with a regex (if you have a problem, use regexes and you will have two problems).

@jrudge-kcom did you see a `Unhandled reference value found: something` error message? You should have if I really catched the problem...

**Comment by jrudge-kcom** [comment]
@marco-hoyer Yes I believe it was something along those lines.

**Comment by rayhwangkcom** [comment]
@marco-hoyer no way! Regex is the way forward. 

Question: when can we realistically expect a release install-able via pip?

**Comment by marco-hoyer** [comment]
@rayhwangkcom yesterday :-D
