### ISSUE TITLE
Disable Rollback on Failure Debug Feature

### ISSUE THREAD

**Issue by jrudge-kcom** [cfn-sphere/cfn-sphere#137]
Would it be possible to add in an option to disable rollback on failure for stack debugging? This is useful if things don't deploy correctly and you need to investigate (Especially instances). You currently have it as OnFailure='DELETE'  in the code, there is an additional option for Rollback which allows you to leave things in place. However you cannot specify both. 

DisableRollback='True',

Maybe it could be toggled and linked to something like a --debug switch or by specifying debug in the configuration file at the top with the timeouts?

Jonathan

**Comment by marco-hoyer** [comment]
Good point. Will add this soon.
