### ISSUE TITLE
Generate change set

### ISSUE THREAD

**Issue by rayoogmy** [cfn-sphere/cfn-sphere#142]
Hi,

I've created a mini-patch to generate change sets. It's not pretty but it's functional. We could do with getting this tidied up into main release.

Todo:
- delete change set when done
- error checking
- print out when there are no changes 
- do something smarter when it's a new stack

It's nothing smart - just need it!

[change_set.txt](https://github.com/cfn-sphere/cfn-sphere/files/1074686/change_set.txt)

**Comment by rayhwangkcom** [comment]
Just realised that there was an existing ticket with some implementation! 

Is it possible to get the change set feature released?

**Comment by marco-hoyer** [comment]
Hi @rayhwangkcom, could you please create a pull request for your changes? This would heavily ease discussions and integration of your changes.

**Comment by rayhwangkcom** [comment]
Hi - I don't seem to have access to push.

**Comment by marco-hoyer** [comment]
Thats true, you will have to create a fork within your account, commit changes there and create a pull request from this. This is really easy with GitHub. Maybe this will help a bit: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by rayhwangkcom** [comment]
https://github.com/cfn-sphere/cfn-sphere/pull/143
