### ISSUE TITLE
Allow usage of environment variables in YAML config

### ISSUE THREAD

**Issue by rayoogmy** [cfn-sphere/cfn-sphere#145]
Pull request open:

https://github.com/cfn-sphere/cfn-sphere/pull/144

**Comment by marco-hoyer** [comment]
Hi, could you explain a bit what you want to achieve with this change? As of what I understand it somehow sacrifices the idea of a self-contained configuration file which describes the truth about how stacks should look like.

**Comment by rayhwangkcom** [comment]
Hi,

Imagine you have 3 environments: development, staging and production.

In theory, main CFN Sphere yaml file sets are the same across all environments with the difference being the parameters such as instance size, CIDR block definitions etc. Without dynamically generating the yaml the easiest way is to be able set the correct parameters in environment variables (and store them in files) per environment. This way a change to a parameter does not require change to the CFN Sphere YAML.

**Comment by h1f1x** [comment]
As far as I know, you can override or set the parameters of a stack on the commandline, when calling cf sync ...
