### ISSUE TITLE
Not compatible with networksx 2.x

### ISSUE THREAD

**Issue by mcbain** [cfn-sphere/cfn-sphere#151]
Version 2.0 of networkx was released at 2017-09-20 and cfn-sphere doesn not specify a requires to 1.x version and fails with:

`module' object has no attribute 'topological_sort_recursive`

Workaround ist to install 1.x version manually - `sudo pip install networkx==1.11`

https://networkx.github.io/documentation/stable/release/release_2.0.html

**Comment by mcbain** [comment]
version 2.0 of networkx was released at 2017-09-20

**Comment by marco-hoyer** [comment]
fix is there and will be released shortly
