### ISSUE TITLE
Unsupported cfn intrinsic function tag found: '!condition'

### ISSUE THREAD

**Issue by h1f1x** [cfn-sphere/cfn-sphere#152]
When using the Cloudformation intrinsic funktion: Condition in my template I get an error.

`ERROR: Could not load file from templates/vpc.yaml: Unsupported cfn intrinsic function tag found: '!condition'`

further reading for these functions: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html

I think it is only missing in the loader.

**Comment by marco-hoyer** [comment]
looks good, thanks for your contribution
