### ISSUE TITLE
missing cfn intrinsic function: !Split

### ISSUE THREAD

**Issue by h1f1x** [cfn-sphere/cfn-sphere#160]
Missing the !Split [1] function, which leads to the following error:
```ERROR: Could not load file from templates/target-db.yaml: Unsupported cfn intrinsic function tag found: '!split'```

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html

**Comment by marco-hoyer** [comment]
good point :-)

**Comment by marco-hoyer** [comment]
looks good, thanks
