### ISSUE TITLE
Warn users they are using an invalid feature for cfn-sphere

### ISSUE THREAD

**Issue by eduaquiles** [cfn-sphere/cfn-sphere#176]
Users still have the option to run cf sync when under an old version. The problem relies when a feature that was introduced on a newer version is used. One example is: our cloud description files have calls to SSM but one of our colleagues was using a version from cfn-sphere older than 1.0.3 (when support was introduced).

It would be nice if cfn-sphere would fail if an invalid function gets called.

**Comment by marco-hoyer** [comment]
Hi and sorry for the late reply. There is a version check in place which says that you're using an outdated version. I'm not sure if we should have something more. 

Maybe it would make sense to have a minimal_version property in the stack config requiring a minimal version of cfn-sphere to run this config. Would this help your problem?

**Comment by eduaquiles** [comment]
Hi, I don't remember what was happening on that specific case (I think cfn was ignoring the SSM function and just handling it as a plain string).

If we can identify a feature is not supported, would be better to fail fast.

If not, something on those lines you suggested (minimal_version) or created_date, ... would also be fine.
