### ISSUE TITLE
Consider IMPORT_COMPLETE as a valid state

### ISSUE THREAD

**Issue by captainsano** [cfn-sphere/cfn-sphere#188]
**Description**
After importing a resource into an existing CF stack, the state becomes `IMPORT_COMPLETE`. Any further `cf sync ...` is disallowed because `IMPORT_COMPLETE` state is not considered a valid state by cfn-sphere.

**To Reproduce**
1. Follow the guide here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html
2. This will put the stack in `IMPORT_COMPLETE` state.
3. Try `cf sync ...`

**Expected behavior**
`cf sync` succeeds.

**Versions:**
cfn-sphere version 1.0.5

**Comment by marco-hoyer** [comment]
That's a good point. I will have a look. Thanks for reporting

**Comment by marco-hoyer** [comment]
Weird thing. The official documentation does not list the "IMPORT_COMPLETE" stack state but I see it's their. Will be fixed in 1.0.6
