### ISSUE TITLE
Let parameters be KMS encrypted

### ISSUE THREAD

**Issue by hscholz** [cfn-sphere/cfn-sphere#19]
In order to not store passwords unencrypted in some vcs, these passwords should be encrypted in the stacks file.

**Comment by marco-hoyer** [comment]
Hi, this feels complicated to me. Implementing KMS features in cfn-sphere would enable us to store encrypted credentials in stack-configuration files but these secrets would have to go a big part of the track in clear text. Imagine cfn-sphere decrypting text on stack create/update. CloudFormation would get and see the clear-text string, also would ec2 inside the user-data field. Furthermore the CloudTrail audit logging would also see clear-text credentials.
I would prefer the ec2 instance to do the decryption job which is already implemented in http://stups.readthedocs.org/en/latest/components/taupage.html but if you use ECS or Beanstalk, this will not work for you. Any suggestions?

Greets, Marco

**Comment by hscholz** [comment]
Cloudformation won't return the passwords if you set NoEcho: true. That let's you solve something like creating a RDS instance but doesn't do that for the client side.

**Comment by marco-hoyer** [comment]
fixed by: https://github.com/cfn-sphere/cfn-sphere/commit/70607134ec1417a19dc744409070674db8c8195c

**Comment by marco-hoyer** [comment]
integration test is ok, looks good
