### ISSUE TITLE
Crash while syncing stack on jenkins agent

### ISSUE THREAD

**Issue by mpoksvl** [cfn-sphere/cfn-sphere#190]
Following stack trace occured while deploying application (syncing stack):

19:21:20  09.07.2020 17:21:13 ERROR: Failed with unexpected error
19:21:20  09.07.2020 17:21:13 ERROR: 'Message'
19:21:20  Traceback (most recent call last):
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/cli.py", line 90, in sync
19:21:20      StackActionHandler(config).create_or_update_stacks()
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/__init__.py", line 53, in create_or_update_stacks
19:21:20      self.cfn.update_stack(stack)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 391, in update_stack
19:21:20      self.wait_for_stack_action_to_complete(stack.name, "update", stack.timeout)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 442, in wait_for_stack_action_to_complete
19:21:20      timeout)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 464, in wait_for_stack_event
19:21:20      events = self.get_stack_events(stack_name)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/util.py", line 170, in wrapper
19:21:20      return function(*args, **kwds)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/aws/cfn.py", line 132, in get_stack_events
19:21:20      raise CfnSphereBotoError(e)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/exceptions.py", line 51, in __init__
19:21:20      self.parse_boto_client_error(e)
19:21:20    File "/usr/local/cfn-sphere/lib/python2.7/site-packages/cfn_sphere/exceptions.py", line 57, in parse_boto_client_error
19:21:20      message = error["Message"]
19:21:20  KeyError: 'Message'

source: https://myscout-ci.fizz.cloud.scout24.com/job/Kapibara/job/Deployment/job/tuv-myscout-web-deployment/3466/console

**Versions:**
 - OS: MaxOD 10.15
 - python: 2.7
 - can-sphere: Included in Jenkins agent

**Comment by marco-hoyer** [comment]
Sorry, I didn't see this issue. Is it still valid? Could you please report the version of boto3 you're using? This error looks weird to me.
