### ISSUE TITLE
AWS Conditions in templates

### ISSUE THREAD

**Issue by cwr10010** [cfn-sphere/cfn-sphere#27]
to provide if/else in templates we would like to have AWS Conditions support in templates.

See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html

IE we need this to differ between HTTP and HTTPS on launch configurations, depending on if a parameter is set or not.

**Comment by marco-hoyer** [comment]
This seems to be a bug. Can you please provide me with an example template?

**Comment by cwr10010** [comment]
It is about adding support for some more AWS::CFN functions like Fn::If or Fn::Not

**Comment by marco-hoyer** [comment]
Thought twice about it. Can you provide me with an example template causing problems? There should be no problem at all with something like "Fn::If" in the templates.

**Comment by cwr10010** [comment]
As inline JSON is available inside the templates this can be closed, albeit a consistent syntax would be great!

**Comment by marco-hoyer** [comment]
Cfn-Sphere is not designed to supply a consistent setup for all cfn functions. One major goal is to simplify cloudformation stack and template handling without forcing users to use cfn-sphere specific syntax.
