### ISSUE TITLE
 ...in ROLLBACK_COMPLETE state and can not be updated.

### ISSUE THREAD

**Issue by jbspeakr** [cfn-sphere/cfn-sphere#28]
Does this really makes sense? In my eyes, a former successful rollback should not prevent further stak updates...

> ROLLBACK_COMPLETE: Successful removal of one or more stacks after a failed stack creation or after an explicitly canceled stack creation. Any resources that were created during the create stack action are deleted.

**Comment by marco-hoyer** [comment]
You're absolutely right but this is cloudformation behavior. If a stack fails to create by accident or user interaction, cloudformation executes a rollback meaning to delete all previously created resources. The stack itself stays in place in a rollback_completed state to enable users to inspect and debug the problems. It is not possible to create this stack again. Users have to delete the stack on their own. The error you get is what cloudformation api returns and nothing in scope of cfn-sphere. Cfn-sphere could maybe detect this state and call delete_stack prior to the create_stack call but this might not be the best solution for anybody. Furthermore this state is hard to detect since it is simply rollback_completed.

**Comment by jbspeakr** [comment]
yeah, I feared it would be that way..

**Comment by azarethcz** [comment]
Yea, me too how fix it?

**Comment by marco-hoyer** [comment]
There is no real fix for this other than manually deleting the stack. I think the underlying concept is that AWS wants you to be able to see the error which caused the stack creation to fail. Thats why a stack creation is rolled back but the stack itself stays in place.

There is a workaround available. You can configure the behaviour of this in your stack configuration:
```
on_failure: 'DO_NOTHING'|'ROLLBACK'|'DELETE'
```

How this looks like in your stack config:
```
region: eu-west-1
on_failure: ROLLBACK #configures for all stacks in this config file
stacks:
  my-stack:
    on_failure: DELETE #configures explicitly for my-stack
    ...
```

**Comment by JimTheMan** [comment]
I was also confused by what he meant by, "delete the stack", but then I found the button hidden away in the "Other Actions" dropdown on the CloudFormation page for that stack.

![chyeah](https://user-images.githubusercontent.com/5354163/45435965-b6df7600-b67f-11e8-9bae-2288312b67eb.png)

**Comment by benjammin12** [comment]
If you have dependencies on the stack, deleting isn't always an option or as easy as you would like. 

I was able to use 
`aws cloudformation continue-update-rollback --resources-to-skip <resourceName>` 
to get around this.

See:
https://matthewrwilton.wordpress.com/2017/01/11/fixing-a-cloudformation-rollback-loop/
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/continue-update-rollback.html

**Comment by BhavinIoT** [comment]
+1 deleting the stack should not be the only option. There should be an option to ignore the ROLLBACK_COMPLETE state (or maybe even other similar states?) and just force an update

**Comment by marco-hoyer** [comment]
@BhavinIoT I'm not sure if this is something cfn-sphere should cover. It is the behaviour of the AWS API. And it is a bit more complicated than it might seem to be. If a stack update fails the stack will be in a ROLLBACK_COMPLETE state but can be updated without any problems. If the stack creation fails it will also be in ROLLBACK_COMPLETE state at the end. And only then another update is not possible. It would be relatively hard to catch this correctly in cfn-sphere and I definitely prefer to keep thinks simple.

**Comment by simonbuchan** [comment]
Don't confuse `ROLLBACK_COMPLETE` (create failed, all created resources deleted) and `UPDATE_ROLLBACK_COMPLETE` (update failed, all created resources deleted, all updated resources updated back to previous state) and `{,UPDATE_}ROLLBACK_FAILED` (tried to rollback after a create or update failure, but then hit an error, unknown state).

You can always safely delete `ROLLBACK_COMPLETE`, it exists only to report the error.

**Comment by movingelectrons** [comment]
how does one delete the stack using the CLI?

**Comment by MemphisMeng** [comment]
> There is no real fix for this other than manually deleting the stack. I think the underlying concept is that AWS wants you to be able to see the error which caused the stack creation to fail. Thats why a stack creation is rolled back but the stack itself stays in place.
> 
> There is a workaround available. You can configure the behaviour of this in your stack configuration:
> 
> ```
> on_failure: 'DO_NOTHING'|'ROLLBACK'|'DELETE'
> ```
> 
> How this looks like in your stack config:
> 
> ```
> region: eu-west-1
> on_failure: ROLLBACK #configures for all stacks in this config file
> stacks:
>   my-stack:
>     on_failure: DELETE #configures explicitly for my-stack
>     ...
> ```

Is it on YAML file? Where did you edit it?
