### ISSUE TITLE
AWS API call should retry with exponential backoff 

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#31]
Cfn-Sphere should retry AWS API calls with exponential retry if f.e. a ThrottleError occurs.

http://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by marco-hoyer** [comment]
done

**Comment by marco-hoyer** [comment]
@esc could you give it a review please?

**Comment by esc** [comment]
looks good to me, though I haven't tried it in practice.

**Comment by esc** [comment]
suggest to close and re-open in case of bugs.
