### ISSUE TITLE
stack sync fails if sns topic is included

### ISSUE THREAD

**Issue by mirkoprescha** [cfn-sphere/cfn-sphere#47]
sns topics can not be updated via cloudformation.

cfn-sphere refers this error:
ERROR: Failed to create <stack-name> (Reason: Update to resource type AWS::SNS::Topic is not supported.)

Is there a plan to change handling of sns topics in cfn-sphere.
 Example: create sns topics if not exisits. Ignore (warning) updates if one exists.
Or does it mean we can not use sns topics in cfn-sphere?

**Comment by marco-hoyer** [comment]
Hi, this is nothing cfn-sphere can do. The error message is directly from the cloudformation API. I don't know why but cloudformation is not able to update sns topics. You can use them but never update them unless cloudformation updates the topic resource to allow updates. See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html.
I do not know any good solution for cfn-sphere. Do you have an idea?

**Comment by mirkoprescha** [comment]
the good thing is, that the sync works, as long as there is no update necessary. 
Otherwise we will delete and create stack.

From my side there is no other solution for cfn-sphere.
