### ISSUE TITLE
automatically tag stacks with stack-configuration source

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#56]
To help reverse engineering of a stacks stack configuration location, cfn-sphere could automatically tag all stacks it manages with a source url to the used stack-configuration when the file is under version control.

**Comment by konz** [comment]
The existing code only works if the stack config is located in the top level directory of the git repo. This is often not the case in bigger projects. Will fix this by traversing upwards until either at `/` or valid git repo found.
