### ISSUE TITLE
Include a `--profile` switch

### ISSUE THREAD

**Issue by esc** [cfn-sphere/cfn-sphere#58]
The `cf` command currently does not have a `--profile` switch which makes it impossible to work with alternative AWS profiles. `awscli` has this and it would be super convenient if `cfn-sphere` had this too.

**Comment by marco-hoyer** [comment]
I'm not that sure about that profiles concept. What is your intention for it. Maybe something like iterating accounts for global deployments?

**Comment by esc** [comment]
No, just for accounts that don't have automation, where I need to deploy stacks.

**Comment by esc** [comment]
I'd like to keep the credentials in my `.aws/credentials` file but don't want them to be used by default.

**Comment by amatthies** [comment]
@esc I had a similar problem, and solved it on my local machine: https://gist.github.com/amatthies/7e78dbb89a49169e3e6f3350e541d1e3

**Comment by marco-hoyer** [comment]
@esc do you really want to have static credentials stored on your machine for longer? :-)

**Comment by esc** [comment]
For AWS accounts that aren't equipped with machinery to handle temporary ones, that is the only choice.

On 30 March 2016 09:45:02 CEST, Marco Hoyer <notifications@github.com> wrote:
>@esc do you really want to have static credentials stored on your
>machine for longer? :-)
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cfn-sphere/cfn-sphere/issues/58#issuecomment-203297473

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jrudge-kcom** [comment]
I would also like to see this feature added. Being able to execute updates from outside the account and being able to switch the target account is very useful.

**Comment by jrudge-kcom** [comment]
I have been playing with this a bit so just some observations . I have setup cross account roles and I can use cfn-sphere with this however it's a little bit messy as you have to set your default AWS_DEFAULT_PROFILE environment variable before cfn-sphere recognises it.  This isn't the largest issue though, the knock on effect is that as I have an MFA and cfn-sphere is not calling the CLI with the --profile script it doesn't cache the token, so I therefore have to enter the MFA every time I run cf sync which is a bit frustrating.

**Comment by marco-hoyer** [comment]
Sounds legit. I will investigate how to do this with boto3. How would you like AWS profiles to be configured? Really with `cf sync --profile` e.g. `CFN_SPHERE_AWS_PROFILE` env var?

**Comment by jrudge-kcom** [comment]
It would be better if it was passed on the command line I think. Default profile unless a --profile switch is specified.

**Comment by nathkc** [comment]
Have looked into this. The fiddly bit is caching MFA credentials as @jrudge-kcom mentioned. This is part of [awscli](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/assumerole.py) rather than boto3, so would need similar code here.

Wondering if CLI cache reuse should be a separate project imported by cfn-sphere, as there's plenty of folk [reinventing the wheel](https://github.com/hashbrowncipher/aws-roleshell#similar-projects).

**Comment by robgott** [comment]
you can use standard boto env var `AWS_PROFILE=XXX` for this, works fine with MFA using the standard params in your `~/.aws/config` file

**Comment by marco-hoyer** [comment]
thanks @robgott for this hint. Sounds good enough to not to add a parameter to cfn-sphere.
