### ISSUE TITLE
Add a dependsOn tag to every stack which has dependencies introduced by cross stack referencing

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#60]
To improve visibility into stack dependencies, such a tag could be a good idea.

**Comment by jrudge-kcom** [comment]
We have found situations where we have had to force dependencies with dummy input parameters relying on dummy outputs from other stacks to force an order.

**Comment by marco-hoyer** [comment]
Ok, this issue is more about increasing transparency by tagging stacks with their dependent stacks. Don't think that this would help you. Or do you have a problem with the dependency management maybe ignoring a dependency?

**Comment by jrudge-kcom** [comment]
@marco-hoyer We find situations where there isn't a dependency resolved between stacks as whilst there is  no reference directly from one stack to another, the resource being created effects another which does have a a dependency. One such example is ECS services depending on the hosts which the containers will run on existing before the service will successfully deploy.
