### ISSUE TITLE
Allow using AWS credentials stored in user home

### ISSUE THREAD

**Issue by henningp** [cfn-sphere/cfn-sphere#63]
I usually run AFP in `--write` mode, as that preserves history in the shell and provides credentials to applications run from an IDE.

However, cfn-sphere requires to use the sub-shell mode, and otherwise fails with a HTTP 403 error.

    $ afp is24-data-pro --write
    Password for hpetersen: 
    $ cf sync osud-events-pro-blue.yaml 
    AWS API Error: BotoServerError: 403 Forbidden
    <ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
      <Error>
        <Type>Sender</Type>
        <Code>InvalidClientTokenId</Code>
        <Message>The security token included in the request is invalid.</Message>
      </Error>
      <RequestId>368c09a7-ec1a-11e5-90fe-c7b170ec5dde</RequestId>
    </ErrorResponse>

Would it be possible to allow using the credentials from user home?

**Comment by marco-hoyer** [comment]
Hi, are you using python3?

**Comment by henningp** [comment]
No, it looks like I'm on 2.7.10.

**Comment by marco-hoyer** [comment]
Can you please verify that the correct credentials are being used by executing `cf sync --debug osud-events-pro-blue.yaml `. It seems as if the SDK finds some credentials but probably old ones.

**Comment by henningp** [comment]
The `--debug` output is unfortunately the same:

```
$ cf sync --debug osud-events-pro-blue.yaml
AWS API Error: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>449d4ceb-ec26-11e5-a807-8fb637ed6217</RequestId>
</ErrorResponse>
```

If I delete ~/.aws/credentials, I get a different error:

```
rm ~/.aws/credentials
cf sync osud-events-pro-blue.yaml
Authentication error! Please check credentials: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

When I get fresh credentials, the original error reappears.

```
$ afp is24-data-pro --write
$ cf sync --debug osud-events-pro-blue.yaml
AWS API Error: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>d6581fa1-ec26-11e5-b6db-9bddc5acce90</RequestId>
</ErrorResponse>
```

So it looks like it finds the credentials, but somehow fails to properly use them. Weird.

**Comment by esc** [comment]
@henningp you could also use the export tricks from here:

https://github.com/immobilienscout24/afp-cli#show-and-export

Could you try that, and see if it makes any difference?

Anothe idea is that your boto is perhaps old, could you try updating it?

**Comment by esc** [comment]
@henningp if you don't make any progress, feel free to come upstairs or ask me to come downstairs via slack, I'm happy to help.

**Comment by henningp** [comment]
Googling around, it looks like boto 2.x does not support  ~/.aws/credentials, but expects a boto-specific configuration file instead. The current version, boto3, supports  ~/.aws/credentials.

I'd supply a pull request to migrate to boto3, but I have never worked with Python.

**Comment by esc** [comment]
Yeah, that might be a bit much... I think it is quite alot and we haven't done this yet, because there wasn't anything to be gained by it, maybe now there is.

cc @cwr10010

**Comment by schlomo** [comment]
+1 for switching to boto3 :-)

**Comment by marco-hoyer** [comment]
Boto supports ~/.aws/credentials but it seems as if there was an update to the ConfigParser module which is used by Boto causing the issue: https://github.com/boto/boto/issues/3458.
The bug doesn't get that much of attention. Switching to boto3 could be a good idea to workaround this issue.

**Comment by marco-hoyer** [comment]
I'm almost done with migration to boto3 which will also resolve this issue. It is done in: https://github.com/cfn-sphere/cfn-sphere/tree/boto3-migration

**Comment by esc** [comment]
@marco-hoyer cool!

**Comment by marco-hoyer** [comment]
new boto3 code is in master now and has no problems with with credentials as I can see. The fix will be included within the next release.

**Comment by henningp** [comment]
Neat! Thanks.
