### ISSUE TITLE
redeploy subcommand

### ISSUE THREAD

**Issue by esc** [cfn-sphere/cfn-sphere#68]
I'd like to see a ``redeploy`` subcommand or similar.. That will ``delete`` and ``sync``.

**Comment by schlomo** [comment]
Deleting *all* the stacks can be quite dangerous and not intended. Like `rm -Rf /` for AWS

**Comment by marco-hoyer** [comment]
I think this is more about deleting all the stacks defined in one stack-configuration. @esc What use case do you see here? A redeploy feels a bit strange from my perspective.

**Comment by esc** [comment]
yeah, sometimes I have `latest` as a docker parameter and would like to deploy the latest `latest`. Doing a delete and sync is the only option in this case.

**Comment by cwr10010** [comment]
So this redeploy may require a know stack-name from the given parameter file?

**Comment by esc** [comment]
Currently I want a replacement for ``cf delete -c stack.yaml && cf sync -c stack.yaml``

**Comment by cwr10010** [comment]
As Schlomo stated I also think this is to dangerous. Nevertheless to redeploy a single stack might be useful. And we can also add a --all then?

**Comment by esc** [comment]
Yes, and I can always have a shell alias for my current use-case.

**Comment by marco-hoyer** [comment]
@esc you could use a modifier to trigger updates in such a case where you want to use latest as version tag for your docker image. Something like `cf sync my-stack.yml --parameter my-stack.updateDate=2016-03-24`. If you use the `updateDate` parameter as a tag for your instances and as a dummy variable inside the user-data of your instance, it will trigger a redeploy whenever it changes. 
This way you would have a traceability for the software version used on your instances and trigger updates as you like it without the need to recreate the stack.

Or, don't use latest ;-)

**Comment by esc** [comment]
Ah, yes that is nice. To not use latest, I'd need additional tooling locally, to resolve whatever 'latest' means.

**Comment by schlomo** [comment]
In keeping with our traditions, I would call this parameter "junk" to
emphasize it's significance :-)
Am 24.03.2016 10:52 schrieb "Valentin Haenel" <notifications@github.com>:

**Comment by esc** [comment]
There has got to be a better way!

**Comment by marco-hoyer** [comment]
From my point of view junk would be the worst name to chose for this.

**Comment by marco-hoyer** [comment]
May we close this issue?
