### ISSUE TITLE
Rendered template should not contain empty sections

### ISSUE THREAD

**Issue by cwr10010** [cfn-sphere/cfn-sphere#69]
We had problems deploying certain CloudFormation-stacks under unknown circumstances. Replies from the Amazon support hints us to a problem that CFN-Sphere renders JSON templates that may contain empty sections if they are not used in the YAML file. It seems that the Cloud Formation service has problems with empty sections in the JSON-template.

Also the rendered template should be semantically equal to the written yaml-template. The empty sections add semantics which is out of control of the creator of the yaml-template.

Mail from Amazon support:
```
Hello,

Thank you for reaching out regarding the removal of the sections within your 
CloudFormation template file.

To give you a little of background information regarding the CloudFormation 
template, please see the following Template Anatomy:
{
  "AWSTemplateFormatVersion" : "version date",

  "Description" : "JSON string",

  "Metadata" : {
    template metadata
  },

  "Parameters" : {
    set of parameters
  },

  "Mappings" : {        <----- Remove this empty section from your template
    set of Mappings
  },

  "Conditions" : {       <----- Remove this empty section from your template as well
    set of conditions
  },

  "Resources" : {
    set of resources
  },

  "Outputs" : {
    set of outputs
  }
}

There are two sections in the template, named Mappings and Conditions, that 
were empty in your template structure that should be removed. Using the above 
as reference please remove these sections from your template and then attempt 
to perform the creation again.
```

**Comment by schlomo** [comment]
+1

**Comment by schlomo** [comment]
You can close this issue. After additional discussion with the AWS support we got the clarification that empty sections are not a problem.
