### ISSUE TITLE
Implement ChangeSet feature

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#71]
AWS introduced a new feature for change prediction called change sets (https://aws.amazon.com/de/blogs/aws/new-change-sets-for-aws-cloudformation/?sc_channel=sm&sc_campaign=launches_2016&sc_publisher=tw_go&sc_content=change_sets_cloudformation&sc_country=global&sc_geo=global&sc_category=cloudformation&adbsc=social_20160329_59922656&adbid=714956683982741504&adbpl=tw&adbpr=66780587). This is what cfn-sphere should support to allow users to see what a change to their template or parameters will do with their infrastructure.

**Comment by jrudge-kcom** [comment]
I would like to +1 this. This would pretty much seal the deal and be the icing on the cake with us now. The ability to have a change set displayed as part of a Sync is invaluable to us. There is another project Stack_Master that does this if you wanted to check out there implementation (it's ruby based however).

**Comment by jrudge-kcom** [comment]
If ChangeSets is too difficult would it be feasible to have a switch which just tells you if there are updates to be performed but not actually update the stacks? So you could just get a report of which stacks are in sync and which aren't. They could just report "Out of Sync"?
