### ISSUE TITLE
Print output variables after cf sync

### ISSUE THREAD

**Issue by schlomo** [cfn-sphere/cfn-sphere#75]
cfn-sphere shows the input variables it used. It would be nice if it would also show the outputs of each stack after it finishes working on a stack.

**Comment by marco-hoyer** [comment]
Yes, good point. I already thought about this but was not sure if somebody needs it. I think it would be best to have this configurable.

**Comment by h1f1x** [comment]
+1
at the moment I go around this with something like this:
    aws cloudformation describe-stacks --stack-name YOURSTACKNAMEHERE | jq '.[]|.[]|.Outputs'

**Comment by matey-jack** [comment]
Hi Marco, my team also wants this and I'd like to help with it. Do you already have it in progress?
