### ISSUE TITLE
CloudFormation throtteling errors not handled by retry

### ISSUE THREAD

**Issue by konz** [cfn-sphere/cfn-sphere#78]
Despite having `@with_boto_retry()` throtteling errors pop up from time to time. e.g.:
```
07.04.2016 11:58:08 INFO: Will process stacks in the following order: pda-test-pictures, pda-test-topics, pda-test-queues, pda-test-database, pda-test
07.04.2016 11:58:09 INFO: Stack pda-test-pictures does not need an update
07.04.2016 11:58:09 INFO: Stack pda-test-topics does not need an update
07.04.2016 11:58:10 INFO: Stack pda-test-queues does not need an update
07.04.2016 11:58:10 INFO: Subscribing queue pda-test-queues-realEstatesQueue-2HRAV3F4IB67 to topic arn:aws:sns:eu-west-1:123456789012:topic-realestate-tuv03 in eu-west-1
07.04.2016 11:58:12 INFO: Stack pda-test-database does not need an update
07.04.2016 11:58:14 ERROR: Could not get latest value for dockerImageVersion: Throttling: Rate exceeded
```

**Comment by marco-hoyer** [comment]
Hi @konz. You're right. The get_latest_taupage_image_id() method call does not have the annotation for boto retry. I'm actually porting cfn-sphere to boto3 where I already fixed this. I wouldn't fix it in the old code for now. Is this ok for you?

**Comment by konz** [comment]
perfectly ok. But I think the problem is that in case of stack parameter handling `BotoServerError` which would trigger retry is catched and rethrown as `CfnSphere...`, so it never gets through to the retry annotation.

btw: did you check this one? https://github.com/boto/botocore/blob/master/botocore/retryhandler.py
Not sure what it is used for or how to use it..

**Comment by marco-hoyer** [comment]
You're right. I fixed the annotation to watch for CfnSphereBotoError exceptions. The botocore retry feature requires client specific configuration as I understand it. Didn't find a solution to configure it in code which makes me think that it is a bad idea as a generic approach to retry throttled requests.
