### ISSUE TITLE
Cfn-Sphere creates random order user-data for @taupageUserData with python3

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#81]
Since dicts are really unordered in python3 (but are pseudo ordered in python2), the order of the transformed user-data lines is more or less random when executed with python3. This causes every sync call to update a stack, even if nothing really changed.

**Comment by esc** [comment]
Suggest to use OrderdDict from the collections module.

On 19 April 2016 18:06:00 CEST, Marco Hoyer <notifications@github.com> wrote:
>Since dicts are really unordered in python3 (but are pseudo ordered in
>python2), the order of the transformed user-data lines is more or less
>random when executed with python3. This causes every sync call to
>update a stack, even if nothing really changed.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cfn-sphere/cfn-sphere/issues/81

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marco-hoyer** [comment]
@esc I tried but since yaml and json parsing returns a plain dict I have to order it to get a deterministic result. The final result is more or less a list which is now created from a sorted dict. As I can see from the tests, this seems to work very well. Do you see any problems there?

**Comment by esc** [comment]
Where are the tests? And yes, ordering the dict explicitly (alphabetically) would suffice.

**Comment by marco-hoyer** [comment]
here: https://github.com/cfn-sphere/cfn-sphere/blob/master/src/unittest/python/template/transformer_tests.py#L247
