### ISSUE TITLE
Propagate tags from stack definition to templates - buggy

### ISSUE THREAD

**Issue by h1f1x** [cfn-sphere/cfn-sphere#82]
When I tag things in stack.yaml, I would like to have all created ressources to be tagged as well. Like a global tag propagating down to all ressources.
At the moment this seems to be done, only when creating the resource (like in the example the kinesis stream). When updating, tag values are not updated on the resource.

See stack.yaml

    region: eu-west-1
    tags:
      usecase: test
      owner: felix
    stacks:
      kinesis:
        template-url: kinesis.yaml

template-url: kinesis.yaml
    
    Resources:
      KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 1

deploy with:

    $ cf sync stack.yaml --confirm
    26.04.2016 17:29:34 INFO: Creating stack kinesis from template kinesis.yaml with parameters:
    +-----------+-------+
    | Parameter | Value |
    +-----------+-------+
    +-----------+-------+
    26.04.2016 17:29:34 INFO: Stack create started
    26.04.2016 17:29:45 INFO: StackEvent AWS::Kinesis::Stream KinesisStream CREATE_IN_PROGRESS
    26.04.2016 17:29:45 INFO: StackEvent AWS::Kinesis::Stream KinesisStream CREATE_IN_PROGRESS
    26.04.2016 17:30:15 INFO: StackEvent AWS::Kinesis::Stream KinesisStream CREATE_COMPLETE
    26.04.2016 17:30:15 INFO: Stack create completed after 39s
    26.04.2016 17:30:15 INFO: Create completed for kinesis

Check tags of cloudformation:

    aws cloudformation describe-stacks --stack-name kinesis |jq '.[]|.[]|.Tags'
    [
      {
        "Value": "felix",
        "Key": "owner"
      },
      {
        "Value": "test",
        "Key": "usecase"
      }
    ]

Now check tags on Resource:

    $ aws kinesis list-tags-for-stream --stream-name kinesis-KinesisStream-N0GVQO4GXGSY
    {
        "HasMoreTags": false,
        "Tags": [
            {
                "Value": "felix",
                "Key": "owner"
            },
            {
                "Value": "test",
                "Key": "usecase"
            }
        ]
    }

Hmmm. There are tags !! But updating the stack.yaml does not update the resource tags ....

**Comment by h1f1x** [comment]
it works ! Oops.

**Comment by marco-hoyer** [comment]
Hi, this is not possible so far by cloudformation. you must tag the individual resources which support tagging.

**Comment by h1f1x** [comment]
updated the first comment above ....
propagating tagging works, but not updating. Bug or feature or side effect ?!

**Comment by marco-hoyer** [comment]
I have not seen this before. When I tested this some month ago, there was no propagation of the stacks tags to its resources. Did the tags properly update on stack level? We might need to dig deeper into this.

**Comment by h1f1x** [comment]
Yes, the tags did update on stack level!

**Comment by marco-hoyer** [comment]
Ok, interesting. What should we do about this? I didn't find anything about how cfn-sphere could help here. This sounds more like a feature request for aws to properly handle tags in cfn stacks.

**Comment by konz** [comment]
Creating and updating tags works as described [in the CloudFormation docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html)

There is no need to explicitely tag resources in the template, as CloudFormation tags all the resources that support tagging.

However the resource type for Kinesis does not support updates, so updated tags might not recreate the Kinesis stream.
