### ISSUE TITLE
Add return values to create_or_update_stacks and delete_stacks

### ISSUE THREAD

**Issue by nmohaupt** [cfn-sphere/cfn-sphere#86]
We use cfn-sphere as an API in a python project. We need to trigger subsequent action if an update has happend. (if update_happend do A else B) 
For such case it would be helpful to have return values from the function indication whether a update or delete occured.

**Comment by marco-hoyer** [comment]
Would it be ok for you to get:
- True: if update happened
- False: if not
- Exception: on error

**Comment by nmohaupt** [comment]
Valentin suggested to use a result object, which is an idea i really like. So you can a result with a dedicated results and errors or something for multiple stacks.

**Comment by marco-hoyer** [comment]
Ah Ok. You seem to want this for create_or_update_stacks() call?! In this case a result object might be the much better choice. I would say it would be best to give it a try.

**Comment by nmohaupt** [comment]
I think it would be good to discuss the format of the result object before trying because this will be our API and can not be change easily afterwards!

I would suggested something like that:

`{
	"results": [{
		"stackName": "foobar",
		"errors": [{
			"id": "timeout",
			"message": "connection timed out during stack update"
		}]
	}]
}`

**Comment by esc** [comment]
Well, what you wrote is a serialization or marshalled version of the object. How about:

```
class CFNUpdateResult(object):

    def __init__(self, stack_name, status, message):
        ...
```

Where `status` is one of a few pre-defined values, such as `ERROR` `SUCCESS` `NOUPDATE`. You can also use objects and types for this however.

**Comment by nmohaupt** [comment]
your are right, for me api == json...

I would suggest to do a MVP with only a stack_name and status and give back an array of CFNUpdateResult. For the start this would be sufficent and we can extend it if we need specific errors. So we build only what need now and it's really simple.

**Comment by marco-hoyer** [comment]
I would prefer a map<stackname,result> to simplify processing of specific stacks results.

**Comment by marco-hoyer** [comment]
@nmohaupt is this still relevant?

**Comment by nmohaupt** [comment]
I think as there is more urgent stuff to do, I will close this one.

For everybody who might use cfn-sphere as kind of an API this may be a good thing to implement.
