### ISSUE TITLE
How to write { String:String, ... } in yaml

### ISSUE THREAD

**Issue by h1f1x** [cfn-sphere/cfn-sphere#94]
hi,

I tried to explain the ConfigurationProperties line in yaml, but it will not work ...

    {
      "Classification" : String,
      "ConfigurationProperties" : { String:String, ... },
      "Configurations" : [ Configuration, ... ]
    }

    Configurations:
         - Classification: hive-site
            ConfigurationProperties:
               "hive.aux.jars.path:s3://bla.jar"

results in: 

    "Configurations": [
      {
        "ConfigurationProperties": "hive.aux.jars.path:s3://bla.jar",
        "Classification": "hive-site"
      }
    ]

**Comment by marco-hoyer** [comment]
Hi, the indentation seems wrong and the leading minus implies a list in yaml. I'm not sure I get your structure right but maybe the integrated conversion will help you. Take your JSON and put it in a file. With `cf convert foo.json` you will get valid yaml for it. Or maybe use something like http://jsontoyaml.com.

**Comment by h1f1x** [comment]
Thanks. The convert function helps and eventually the website show, that
    
    "ConfigurationProperties" : { String:String, ... },
is not a valid json and only a small glitch in the AWS documentation. Or vise versa: 
I got it wrong ;(

Thanks for helping ;) !
