### ISSUE TITLE
Document stable API

### ISSUE THREAD

**Issue by esc** [cfn-sphere/cfn-sphere#95]
People continuously complain about cfn-sphere lacking a stable api. I would suggest to use the `__all__` feature in the toplevel `__init__.py`:

https://docs.python.org/2/tutorial/modules.html#importing-from-a-package

**Comment by marco-hoyer** [comment]
I didn't know the `__all__` thing. Does this really help implementing a stable api?

**Comment by esc** [comment]
It certainly helps with managing user-visible inputs. You could imagine, that only those functions that are available from the top-level module are designated as stable and therefore should not be changed in backwards-incompatible ways.

**Comment by esc** [comment]
I am no longer interested in this feature and will close it now.
