### ISSUE TITLE
Adding an output to a stack with no other changes does not trigger a stack update

### ISSUE THREAD

**Issue by henningp** [cfn-sphere/cfn-sphere#98]
The stack update is skipped with "Stack xyz does not need an update".

The workaround is to make a change to the stack; still, this is surprising.

**Comment by marco-hoyer** [comment]
Hi, this is how the cloudformation api behaves. Cloudformation only determines changes to resources to decide if an update is needed or not. See this: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html. There is a note at the top of the document addressing this. It is somehow disappointing but nothing cfn-sphere can solve.

**Comment by henningp** [comment]
I see! I assumed the check was something that cfn-sphere did. Thanks!
